title: Leo Xuzhang Lin

email: me@leoxlin.com

description: >-
  Hey friend! Thanks for visting my blog. I am a Software Engineer based in
  Boston, MA. I will be writing about Software, Philosophy, and other topics
  I find interesting in my life.

baseurl: ""

url: "https://blog.leoxlin.com"

twitter_username: leoxlin
github_username:  leoxlin

theme: minima
plugins:
  - jekyll-feed
