title: Leo Xuzhang Lin

email: me@leoxlin.com

description: >-
  Hey friend! Thanks for visting my blog. I am a Software Engineer based in
  Boston, Massachusetts. I write about Software and other topics
  I find interesting in my life.

baseurl: ""

url: "https://blog.leoxlin.com"

homeUrl: "https://www.leoxlin.com"

twitter_username: leoxlin
github_username:  leoxlin

plugins:
  - jekyll-feed
