title: "Duct-Tape Engineer"

email: me@leoxlin.com

description: >-
  Hey there! I’m Leo, a Software Engineer based in Boston. Thanks for visiting
  my blog! Here I write about software, philosophy, and whatever else inspires me.

baseurl: ""

url: "https://blog.leoxlin.com"

homeUrl: "https://www.leoxlin.com"

twitter_username: leoxlin
github_username:  leoxlin

plugins:
  - jekyll-feed
